logging.level.org.springframework.web: DEBUG

server.port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    tomcat:
      max-active: 10
      max-idle: 8
      max-wait: 1000
      min-evictable-idle-time-millis: 1000
      min-idle: 8
      time-between-eviction-runs-millis: 1
    url: 'jdbc:h2:file:~/dasboot'
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true